image: docker:latest

services:
  - docker:dind

before_script:
  - docker build --rm -t gaiaclima . --build-arg API_KEY=$API_KEY

stages:
  - build
  - test
  - quality

buildLocal:
  stage: build
  script:
    - docker build --rm -t gaiaclima . --build-arg API_KEY=$API_KEY

testCheck:
  stage: test
  script:
    - docker run --rm gaiaclima /bin/sh -c "cd /app; npm test"

staticAnalysis:
  stage: quality
  script:
    - docker run --rm gaiaclima /bin/sh -c "cd /app; npm run lint"
