version: '3'

services:
  gaiaclima:
    image: caleberios/gaia-clima:latest
    restart: always
    environment:
      - API_KEY=${API_KEY}
      - ENVIRONMENT=dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: aashreys/mongo-auth:latest
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=gaiaclima
      - MONGODB_ADMIN_PASS=admin123
    command: mongod --port 27018
    ports: 
      - 27018:27018