apiVersion: v1
kind: Service
metadata:
  name: gaia-clima
spec:
  ports:
  - port: 443
    targetPort: 3000
  selector:
    app: gaia-clima
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-clima
spec:
  selector:
    matchLabels:
      app: gaia-clima
  replicas: 2
  template:
    metadata:
      labels:
        app: gaia-clima
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: production
        image: caleberios/gaia-clima:latest
        imagePullPolicy: Always
        name: gaia-clima
        ports:
        - containerPort: 3000