apiVersion: v1
kind: Service
metadata:
  name: gaia-clima-hml
spec:
  ports:
  - port: 443
    targetPort: 3000
  selector:
    app: gaia-clima-hml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gaia-clima-hml
spec:
  selector:
    matchLabels:
      app: gaia-clima-hml
  replicas: 2
  template:
    metadata:
      labels:
        app: gaia-clima-hml
    spec:
      containers:
      - env:
        - name: ENVIRONMENT
          value: homolog
        image: caleberios/gaia-clima:homolog
        imagePullPolicy: Always
        name: gaia-clima-hml
        ports:
        - containerPort: 3000